server:
  port: 8082
spring:
#  cloud:
#    sentinel:
#      transport:
#        dashboard: localhost:8090
#      http-method-specify: true
feign:
  okhttp:
    enabled: true
#  sentinel:
#    enabled: true
hm:
  db:
    database: hm-cart
    swagger:
      title: "黑马商城购物车服务接口文档"
      desc: "黑马商城购物车管理接口文档"
      packege: com.hmall.cart.controller
# keytool -genkeypair -alias hmall -keyalg RSA -keypass hmall123 -keystore hmall.jks -storepass hmall123